name: selection_tree_view
description: "A Flutter package providing a customizable and interactive tree view with selection capabilities."
version: 1.0.3
repository: https://github.com/NamTranDinh/selection_tree_view

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  flutter_bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



